uint8[] data

int8 Time_change
int8 step
int8 Right_Actual
int8 Right_Target
float32 Left_Actual
float32 Left_Target

float32[] pre_postion_left
float32[] pre_error_left
float32[] G_left
float32[] e_left
float32 Kp_left
float32 Ki_left

float32[] pre_postion_right
float32[] pre_error_right
float32[] G_right
float32[] e_right
float32 Kp_right
float32 Ki_right

float32[] out_left
float32[] out_right

string name

