(cl:in-package new_msgs-msg)
(cl:export '(DATA-VAL
          DATA
          TIME_CHANGE-VAL
          TIME_CHANGE
          STEP-VAL
          STEP
          RIGHT_ACTUAL-VAL
          RIGHT_ACTUAL
          RIGHT_TARGET-VAL
          RIGHT_TARGET
          LEFT_ACTUAL-VAL
          LEFT_ACTUAL
          LEFT_TARGET-VAL
          LEFT_TARGET
          PRE_POSTION_LEFT-VAL
          PRE_POSTION_LEFT
          PRE_ERROR_LEFT-VAL
          PRE_ERROR_LEFT
          G_LEFT-VAL
          G_LEFT
          E_LEFT-VAL
          E_LEFT
          KP_LEFT-VAL
          KP_LEFT
          KI_LEFT-VAL
          KI_LEFT
          PRE_POSTION_RIGHT-VAL
          PRE_POSTION_RIGHT
          PRE_ERROR_RIGHT-VAL
          PRE_ERROR_RIGHT
          G_RIGHT-VAL
          G_RIGHT
          E_RIGHT-VAL
          E_RIGHT
          KP_RIGHT-VAL
          KP_RIGHT
          KI_RIGHT-VAL
          KI_RIGHT
          OUT_LEFT-VAL
          OUT_LEFT
          OUT_RIGHT-VAL
          OUT_RIGHT
          NAME-VAL
          NAME
))